-----------------------------------------------------------------------------------------------------------------------------------------
-- PRESET
-----------------------------------------------------------------------------------------------------------------------------------------
Preset = {
	["1"] = {
		["mp_m_freemode_01"] = {
			["hat"] = { item = 109, texture = 2 },
			["pants"] = { item = 31, texture = 1 },
			["vest"] = { item = 1, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 148, texture = 0 },
			["mask"] = { item = 0, texture = 0 },
			["shoes"] = { item = 24, texture = 0 },
			["tshirt"] = { item = 5, texture = 0 },
			["torso"] = { item = 228, texture = 0 },
			["accessory"] = { item = 1, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 11, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		},
		["mp_f_freemode_01"] = {
			["hat"] = { item = -1, texture = 0 },
			["pants"] = { item = 170, texture = 0 },
			["vest"] = { item = 0, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 160, texture = 0 },
			["mask"] = { item = 121, texture = 0 },
			["shoes"] = { item = 9, texture = 0 },
			["tshirt"] = { item = 245, texture = 0 },
			["torso"] = { item = 474, texture = 0 },
			["accessory"] = { item = 137, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 0, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		}
	},
	["2"] = {
		["mp_m_freemode_01"] = {
			["hat"] = { item = 109, texture = 2 },
			["pants"] = { item = 31, texture = 1 },
			["vest"] = { item = 1, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 148, texture = 0 },
			["mask"] = { item = 0, texture = 0 },
			["shoes"] = { item = 24, texture = 0 },
			["tshirt"] = { item = 5, texture = 0 },
			["torso"] = { item = 42, texture = 0 },
			["accessory"] = { item = 1, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 4, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		},
		["mp_f_freemode_01"] = {
			["hat"] = { item = -1, texture = 0 },
			["pants"] = { item = 170, texture = 1 },
			["vest"] = { item = 0, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 158, texture = 0 },
			["mask"] = { item = 121, texture = 0 },
			["shoes"] = { item = 9, texture = 0 },
			["tshirt"] = { item = 245, texture = 0 },
			["torso"] = { item = 474, texture = 3 },
			["accessory"] = { item = 137, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 0, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		}
	},
	["3"] = {
		["mp_m_freemode_01"] = {
			["hat"] = { item = 21, texture = 0 },
			["pants"] = { item = 65, texture = 0 },
			["vest"] = { item = 2, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 148, texture = 0 },
			["mask"] = { item = 121, texture = 0 },
			["shoes"] = { item = 24, texture = 0 },
			["tshirt"] = { item = 5, texture = 0 },
			["torso"] = { item = 42, texture = 0 },
			["accessory"] = { item = 1, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 22, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		},
		["mp_f_freemode_01"] = {
			["hat"] = { item = -1, texture = 0 },
			["pants"] = { item = 170, texture = 2 },
			["vest"] = { item = 0, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 160, texture = 3 },
			["mask"] = { item = 121, texture = 0 },
			["shoes"] = { item = 9, texture = 0 },
			["tshirt"] = { item = 245, texture = 0 },
			["torso"] = { item = 474, texture = 6 },
			["accessory"] = { item = 1, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 0, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		}
	},
	["4"] = {
		["mp_m_freemode_01"] = {
			["hat"] = { item = 29, texture = 0 },
			["pants"] = { item = 87, texture = 9 },
			["vest"] = { item = 3, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 148, texture = 0 },
			["mask"] = { item = 0, texture = 0 },
			["shoes"] = { item = 24, texture = 0 },
			["tshirt"] = { item = 5, texture = 0 },
			["torso"] = { item = 220, texture = 9 },
			["accessory"] = { item = 1, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 22, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		},
		["mp_f_freemode_01"] = {
			["hat"] = { item = -1, texture = 0 },
			["pants"] = { item = 170, texture = 3 },
			["vest"] = { item = 0, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 160, texture = 5 },
			["mask"] = { item = 121, texture = 0 },
			["shoes"] = { item = 9, texture = 0 },
			["tshirt"] = { item = 245, texture = 0 },
			["torso"] = { item = 474, texture = 9 },
			["accessory"] = { item = 1, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 0, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		}
	},
	["8"] = {
		["mp_m_freemode_01"] = {
			["hat"] = { item = 29, texture = 0 },
			["pants"] = { item = 87, texture = 10 },
			["vest"] = { item = 1, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 148, texture = 0 },
			["mask"] = { item = 0, texture = 0 },
			["shoes"] = { item = 24, texture = 0 },
			["tshirt"] = { item = 5, texture = 0 },
			["torso"] = { item = 236, texture = 0 },
			["accessory"] = { item = 1, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 22, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		},
		["mp_f_freemode_01"] = {
			["hat"] = { item = -1, texture = 0 },
			["pants"] = { item = 170, texture = 3 },
			["vest"] = { item = 0, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 160, texture = 5 },
			["mask"] = { item = 121, texture = 0 },
			["shoes"] = { item = 9, texture = 0 },
			["tshirt"] = { item = 245, texture = 0 },
			["torso"] = { item = 474, texture = 9 },
			["accessory"] = { item = 137, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 0, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		}
	},
	-- ["9"] = {
	-- 	["mp_m_freemode_01"] = {
	-- 		["hat"] = { item = 29, texture = 0 },
	-- 		["pants"] = { item = 87, texture = 9 },
	-- 		["vest"] = { item = 3, texture = 0 },
	-- 		["bracelet"] = { item = -1, texture = 0 },
	-- 		["backpack"] = { item = 0, texture = 0 },
	-- 		["decals"] = { item = 148, texture = 0 },
	-- 		["mask"] = { item = 0, texture = 0 },
	-- 		["shoes"] = { item = 24, texture = 0 },
	-- 		["tshirt"] = { item = 5, texture = 0 },
	-- 		["torso"] = { item = 220, texture = 9 },
	-- 		["accessory"] = { item = 167, texture = 0 },
	-- 		["watch"] = { item = -1, texture = 0 },
	-- 		["arms"] = { item = 22, texture = 0 },
	-- 		["glass"] = { item = 0, texture = 0 },
	-- 		["ear"] = { item = -1, texture = 0 }
	-- 	},
	-- 	["mp_f_freemode_01"] = {
	-- 		["hat"] = { item = -1, texture = 0 },
	-- 		["pants"] = { item = 170, texture = 3 },
	-- 		["vest"] = { item = 0, texture = 0 },
	-- 		["bracelet"] = { item = -1, texture = 0 },
	-- 		["backpack"] = { item = 0, texture = 0 },
	-- 		["decals"] = { item = 160, texture = 5 },
	-- 		["mask"] = { item = 121, texture = 0 },
	-- 		["shoes"] = { item = 9, texture = 0 },
	-- 		["tshirt"] = { item = 245, texture = 0 },
	-- 		["torso"] = { item = 474, texture = 9 },
	-- 		["accessory"] = { item = 137, texture = 0 },
	-- 		["watch"] = { item = -1, texture = 0 },
	-- 		["arms"] = { item = 0, texture = 0 },
	-- 		["glass"] = { item = 0, texture = 0 },
	-- 		["ear"] = { item = -1, texture = 0 }
	-- 	}
	-- },
	-- ["10"] = {
	-- 	["mp_m_freemode_01"] = {
	-- 		["hat"] = { item = 29, texture = 0 },
	-- 		["pants"] = { item = 87, texture = 9 },
	-- 		["vest"] = { item = 3, texture = 0 },
	-- 		["bracelet"] = { item = -1, texture = 0 },
	-- 		["backpack"] = { item = 0, texture = 0 },
	-- 		["decals"] = { item = 148, texture = 0 },
	-- 		["mask"] = { item = 0, texture = 0 },
	-- 		["shoes"] = { item = 24, texture = 0 },
	-- 		["tshirt"] = { item = 5, texture = 0 },
	-- 		["torso"] = { item = 220, texture = 9 },
	-- 		["accessory"] = { item = 167, texture = 0 },
	-- 		["watch"] = { item = -1, texture = 0 },
	-- 		["arms"] = { item = 22, texture = 0 },
	-- 		["glass"] = { item = 0, texture = 0 },
	-- 		["ear"] = { item = -1, texture = 0 }
	-- 	},
	-- 	["mp_f_freemode_01"] = {
	-- 		["hat"] = { item = -1, texture = 0 },
	-- 		["pants"] = { item = 170, texture = 3 },
	-- 		["vest"] = { item = 0, texture = 0 },
	-- 		["bracelet"] = { item = -1, texture = 0 },
	-- 		["backpack"] = { item = 0, texture = 0 },
	-- 		["decals"] = { item = 160, texture = 5 },
	-- 		["mask"] = { item = 121, texture = 0 },
	-- 		["shoes"] = { item = 9, texture = 0 },
	-- 		["tshirt"] = { item = 245, texture = 0 },
	-- 		["torso"] = { item = 474, texture = 9 },
	-- 		["accessory"] = { item = 137, texture = 0 },
	-- 		["watch"] = { item = -1, texture = 0 },
	-- 		["arms"] = { item = 0, texture = 0 },
	-- 		["glass"] = { item = 0, texture = 0 },
	-- 		["ear"] = { item = -1, texture = 0 }
	-- 	}
	-- },
	["5"] = {
		["mp_m_freemode_01"] = {
			["hat"] = { item = -1, texture = 0 },
			["pants"] = { item = 20, texture = 0 },
			["vest"] = { item = 0, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 0, texture = 0 },
			["mask"] = { item = 121, texture = 0 },
			["shoes"] = { item = 1, texture = 1 },
			["tshirt"] = { item = 96, texture = 0 },
			["torso"] = { item = 32, texture = 7 },
			["accessory"] = { item = 126, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 79, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		},
		["mp_f_freemode_01"] = {
			["hat"] = { item = -1, texture = 0 },
			["pants"] = { item = 23, texture = 0 },
			["vest"] = { item = 0, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 0, texture = 0 },
			["mask"] = { item = 121, texture = 0 },
			["shoes"] = { item = 1, texture = 0 },
			["tshirt"] = { item = 101, texture = 0 },
			["torso"] = { item = 58, texture = 7 },
			["accessory"] = { item = 96, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 91, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		}
	},
	["6"] = {
		["mp_m_freemode_01"] = {
			["hat"] = { item = -1, texture = 0 },
			["pants"] = { item = 149, texture = 0 },
			["vest"] = { item = 0, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 57, texture = 0 },
			["mask"] = { item = 121, texture = 0 },
			["shoes"] = { item = 25, texture = 0 },
			["tshirt"] = { item = 94, texture = 0 },
			["torso"] = { item = 249, texture = 0 },
			["accessory"] = { item = 127, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 86, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		},
		["mp_f_freemode_01"] = {
			["hat"] = { item = -1, texture = 0 },
			["pants"] = { item = 157, texture = 0 },
			["vest"] = { item = 0, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 65, texture = 0 },
			["mask"] = { item = 121, texture = 0 },
			["shoes"] = { item = 106, texture = 0 },
			["tshirt"] = { item = 71, texture = 1 },
			["torso"] = { item = 257, texture = 0 },
			["accessory"] = { item = 97, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 104, texture = 0 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		}
	},
	["7"] = {
		["mp_m_freemode_01"] = {
			["hat"] = { item = -1, texture = 0 },
			["pants"] = { item = 20, texture = 0 },
			["vest"] = { item = 0, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 0, texture = 0 },
			["mask"] = { item = 0, texture = 0 },
			["shoes"] = { item = 1, texture = 1 },
			["tshirt"] = { item = 15, texture = 0 },
			["torso"] = { item = 146, texture = 6 },
			["accessory"] = { item = 127, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 85, texture = 1 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		},
		["mp_f_freemode_01"] = {
			["hat"] = { item = -1, texture = 0 },
			["pants"] = { item = 23, texture = 0 },
			["vest"] = { item = 0, texture = 0 },
			["bracelet"] = { item = -1, texture = 0 },
			["backpack"] = { item = 0, texture = 0 },
			["decals"] = { item = 0, texture = 0 },
			["mask"] = { item = 0, texture = 0 },
			["shoes"] = { item = 1, texture = 0 },
			["tshirt"] = { item = 2, texture = 0 },
			["torso"] = { item = 141, texture = 1 },
			["accessory"] = { item = 97, texture = 0 },
			["watch"] = { item = -1, texture = 0 },
			["arms"] = { item = 109, texture = 1 },
			["glass"] = { item = 0, texture = 0 },
			["ear"] = { item = -1, texture = 0 }
		}
	}
}