-----------------------------------------------------------------------------------------------------------------------------------------
-- GARAGES
-----------------------------------------------------------------------------------------------------------------------------------------
Garages = {
	["1"] = { name = "Garage", payment = false, license = true },
	["2"] = { name = "Garage", payment = true, license = true },
	["3"] = { name = "Garage", payment = false, license = true },
	["4"] = { name = "Garage", payment = true, license = true },
	["5"] = { name = "Garage", payment = true, license = true },
	["6"] = { name = "Garage", payment = true, license = true },
	["7"] = { name = "Garage", payment = true, license = true },
	["8"] = { name = "Garage", payment = true, license = true },
	["9"] = { name = "Garage", payment = true, license = true },
	["10"] = { name = "Garage", payment = true, license = true },
	["11"] = { name = "Garage", payment = true, license = true },
	["12"] = { name = "Garage", payment = true, license = true },
	["13"] = { name = "Garage", payment = true, license = true },
	["14"] = { name = "Garage", payment = true, license = true },
	["15"] = { name = "Garage", payment = true, license = true },
	["16"] = { name = "Garage", payment = true, license = true },
	["17"] = { name = "Garage", payment = true, license = true },
	["18"] = { name = "Garage", payment = true, license = true },
	["21"] = { name = "Garage", payment = true, license = true },
	["22"] = { name = "Garage", payment = true, license = true },
	["23"] = { name = "Garage", payment = false, license = true },
	["25"] = { name = "Garage", payment = true, license = true },
	["26"] = { name = "Garage", payment = false, license = true },
	["27"] = { name = "Garage", payment = false, license = true },
	["28"] = { name = "Garage", payment = false, license = true },
	["29"] = { name = "Garage", payment = true, license = true },
	["30"] = { name = "Garage", payment = true, license = true },
	["31"] = { name = "Garage", payment = true, license = true },
	["32"] = { name = "Garage", payment = true, license = true },
	["33"] = { name = "Garage", payment = true, license = true },
	["34"] = { name = "Garage", payment = true, license = true },
	["35"] = { name = "Garage", payment = true, license = true },
	["36"] = { name = "Garage", payment = true, license = true },
	["37"] = { name = "Garage", payment = true, license = true },
	["38"] = { name = "Garage", payment = true, license = true },
	["39"] = { name = "Garage", payment = true, license = true },
	["40"] = { name = "Garage", payment = true, license = true },
	["154"] = { name = "Garage", payment = true, license = true },
	["155"] = { name = "Garage", payment = true, license = true },
	["156"] = { name = "Garage", payment = true, license = true },
	["157"] = { name = "Garage", payment = true, license = true },
	["158"] = { name = "Garage", payment = true, license = true },

	["174"] = { name = "Garage", payment = true, license = true },

	["159"] = { name = "Fac", payment = false, license = false, perm = "Favela01" },
	["160"] = { name = "Fac", payment = false, license = false, perm = "Favela02"  },
	["161"] = { name = "Fac", payment = false, license = false, perm = "Favela03"  },
	["162"] = { name = "Fac", payment = false, license = false, perm = "Favela04"  },
	["163"] = { name = "Fac", payment = false, license = false, perm = "Favela05"  },
	["164"] = { name = "Fac", payment = false, license = false, perm = "Favela06"  },
	["165"] = { name = "Fac", payment = false, license = false, perm = "Favela07"  },
	["166"] = { name = "Fac", payment = false, license = false, perm = "Favela08"  },
	["167"] = { name = "Fac", payment = false, license = false, perm = "Desmanche01"  },
	["168"] = { name = "Fac", payment = false, license = false, perm = "Mafia01"  },
	["169"] = { name = "Fac", payment = false, license = false, perm = "Mafia02"  },
	["170"] = { name = "Fac", payment = false, license = false, perm = "Mafia03"  },
	["171"] = { name = "Fac", payment = false, license = false, perm = "Mafia04"  },
	["172"] = { name = "Fac", payment = false, license = false, perm = "Mafia05"  },
	["173"] = { name = "Fac", payment = false, license = false, perm = "Mafia06"  },

	-- Paramedico
	["41"] = { name = "Paramedico", payment = false, license = true, perm = "Paramedico" },
	["42"] = { name = "heliParamedico", payment = false, license = true, perm = "Paramedico" },
	["43"] = { name = "Paramedico", payment = false, license = true, perm = "Paramedico" },
	["44"] = { name = "heliParamedico", payment = false, license = true, perm = "Paramedico" },
	["45"] = { name = "Paramedico", payment = false, license = true, perm = "Paramedico" },

	-- Policia
	["61"] = { name = "Policia", payment = false, license = true, perm = "Policia" },
	["62"] = { name = "heliPolicia", payment = false, license = true, perm = "Policia" },

	-- Prisão
	["67"] = { name = "Policia", payment = false, license = true, perm = "Policia" },
	["68"] = { name = "busPolicia", payment = false, license = true, perm = "Policia" },

	-- Gangs
	["91"] = { name = "Ballas", payment = false, license = true, perm = "Ballas" },
	["92"] = { name = "Families", payment = false, license = true, perm = "Families" },
	["93"] = { name = "Vagos", payment = false, license = true, perm = "Vagos" },
	["94"] = { name = "Aztecas", payment = false, license = true, perm = "Aztecas" },
	["95"] = { name = "Bloods", payment = false, license = true, perm = "Bloods" },

	-- Bikes
	["101"] = { name = "Bikes", payment = false, license = false },
	["102"] = { name = "Bikes", payment = false, license = false },
	["103"] = { name = "Bikes", payment = false, license = false },
	["104"] = { name = "Bikes", payment = false, license = false },
	["105"] = { name = "Bikes", payment = false, license = false },
	["106"] = { name = "Bikes", payment = false, license = false },
	["107"] = { name = "Bikes", payment = false, license = false },
	["108"] = { name = "Bikes", payment = false, license = false },
	["109"] = { name = "Bikes", payment = false, license = false },
	["110"] = { name = "Bikes", payment = false, license = false },
	["111"] = { name = "Bikes", payment = false, license = false },
	["112"] = { name = "Bikes", payment = false, license = false },
	["113"] = { name = "Bikes", payment = false, license = false },
	["114"] = { name = "Bikes", payment = false, license = false },
	["115"] = { name = "Bikes", payment = false, license = false },
	["116"] = { name = "Bikes", payment = false, license = false },
	["117"] = { name = "Bikes", payment = false, license = false },
	["118"] = { name = "Bikes", payment = false, license = false },

	-- Boats
	["121"] = { name = "Boats", payment = true, license = false },
	["123"] = { name = "Boats", payment = true, license = false },
	["124"] = { name = "Boats", payment = true, license = false },
	["125"] = { name = "Boats", payment = true, license = false },
	["126"] = { name = "Boats", payment = true, license = false },

	-- Works
	--["141"] = { name = "Lumberman", payment = false, license = false },
	["142"] = { name = "Driver", payment = false, license = false },
	["143"] = { name = "Garbageman", payment = false, license = false },
	["144"] = { name = "Transporter", payment = false, license = false },
	["146"] = { name = "TowDriver", payment = false, license = false },
	["148"] = { name = "Garbageman", payment = false, license = false },
	["149"] = { name = "Garbageman", payment = false, license = false },
	["150"] = { name = "Taxi", payment = false, license = false },
	["151"] = { name = "Trucker", payment = false, license = false },
	["152"] = { name = "Corrections", payment = false, license = false, perm = "Policia" },
	--["153"] = { name = "PostOp", payment = false, license = false }
}
