fx_version 'adamant'
game 'gta5'

this_is_a_map "yes"

data_file 'DLC_ITYP_REQUEST' 'stream/barraco_103.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/barracos_rdshop.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/calcadafav.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/casas.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/casas2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/casasbarracos.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/casasdj.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_01_metadata_003_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/cs_hlun_lod2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/cs_hlun_lod2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/cs_hlun_lod2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/escadapequena.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/favela_brkk_casas.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/favela_brkk_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/favela_casas.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/favela_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/favela_props2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/garagem_rds_01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/gm_prop_casas.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/gm_prop_casas.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/gunstore.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/on_bridge.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/on_casas1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/on_casas2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/on_casas3.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/on_ruabarragem.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/onarts_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/onarts_props2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/paulistao.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/polonia.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props_rdshop.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props_zn.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props3.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/props4.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/propsquebrada.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/propssom.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/qs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/qs1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/qs324.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/rua_igrejinha_rdshop_01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ruajacarezinho.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ruavine.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/society.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/varalquebradashop.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vbgra.ytyp'

